server:
  port: 8191 
spring:
   cloud:
     config:
       server:
         git:
           uri: https://github.com/Kajanthuka/spring-cloud-config-store.git
           search-paths : 
            -'*service'
            
